#!/bin/bash

[ -n "$MD2PDF_PANDOC_ARGS_LOG" ] && printf '%s\n' "$@" > "$MD2PDF_PANDOC_ARGS_LOG"
[ -n "$MD2PDF_PANDOC_INPUT_LOG" ] && cp "$1" "$MD2PDF_PANDOC_INPUT_LOG"

saved_args=("$@")
while [ "$#" -gt 0 ]; do
  if [ "$1" = "--css" ]; then
    shift
    [ -n "$MD2PDF_PANDOC_CSS_LOG" ] && [ -f "$1" ] && cp "$1" "$MD2PDF_PANDOC_CSS_LOG"
  fi
  shift
done

set -- "${saved_args[@]}"
while [ "$#" -gt 0 ]; do
  if [ "$1" = "-o" ]; then
    shift
    touch "$1"
    exit 0
  fi
  shift
done
